#!/usr/bin/env python3
"""
build_context.py - generate context/gold_models.yml FROM the Task 1 dbt schema.

This removes the duplication: the Gold models are described once, in the Task 1
dbt yaml files (the single source of truth). Task 2's catalog is generated from
them, so it can never silently drift out of sync.

In a production setup the same script would instead read dbt's compiled
`manifest.json` / `catalog.json` (or the warehouse information_schema). Here we
read the dbt schema `.yml` files directly, which is enough for the assignment.

Run:
    cd task2_ai_pipeline
    python scripts/build_context.py
"""

from __future__ import annotations
from pathlib import Path
import datetime
import yaml

ROOT = Path(__file__).resolve().parents[1]
DBT_MODELS_DIR = ROOT.parent / "task1_gold_model" / "models" / "gold"
OUT = ROOT / "context" / "gold_models.yml"


def collect_models(models_dir: Path) -> list[dict]:
    """Read every dbt schema .yml and return [{name, description, columns:[name]}]."""
    models = []
    for yml in sorted(models_dir.glob("*.yml")):
        doc = yaml.safe_load(yml.read_text()) or {}
        for m in doc.get("models", []):
            models.append({
                "name": m["name"],
                "description": (m.get("description") or "").strip(),
                "columns": [c["name"] for c in m.get("columns", [])],
                "source_file": yml.name,
            })
    return models


def write_catalog(models: list[dict], out: Path) -> None:
    header = (
        "# =============================================================================\n"
        "# gold_models.yml  -  AUTO-GENERATED. DO NOT EDIT BY HAND.\n"
        "# Generated by scripts/build_context.py from the Task 1 dbt schema files in\n"
        "# task1_gold_model/models/gold/. Edit the dbt yaml there, then re-run the script.\n"
        f"# Generated: {datetime.date.today().isoformat()}\n"
        "# =============================================================================\n"
    )
    # Clean one-line descriptions and a flat column-name list per model.
    data = {"version": 1, "models": [
        {"name": m["name"],
         "description": " ".join(m["description"].split()),
         "source_file": m["source_file"],
         "columns": m["columns"]}
        for m in models
    ]}
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=1000)
    out.write_text(header + body)


def main() -> None:
    models = collect_models(DBT_MODELS_DIR)
    write_catalog(models, OUT)
    total_cols = sum(len(m["columns"]) for m in models)
    print(f"Wrote {OUT.relative_to(ROOT.parent)}")
    print(f"  {len(models)} models, {total_cols} columns, from {DBT_MODELS_DIR.name}/*.yml")
    for m in models:
        print(f"  - {m['name']}: {len(m['columns'])} cols  (from {m['source_file']})")


if __name__ == "__main__":
    main()
